export enum AuthActionTypes {
  LOADING = "AUTH_LOADING",
  LOG_IN_SUCCESS = "LOG_IN_SUCCESS",
  REGISTER_SUCCESS = "REGISTER_SUCCESS",
  FETCH_PROFILE = "FETCH_PROFILE",
  LOG_OUT = "LOG_OUT",
  ERROR = "AUTH_ERROR",
  CLEAR = "CLEAR_AUTH_ERROR"
}
