export enum TodoActionTypes {
    LOADING = "TODO_LOADING",
    FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS",
    CREATE_TODO = "CREATE_TODO",
    UPDATE_TODO = "UPDATE_TODO",
    DELETE_TODO = "DELETE_TODO",
    TOGGLE_TODO = "TOGGLE_TODO",
    ERROR = "TODO_ERROR",
    CLEAR = "CLEAR_TODO_ERROR"
}
